<?php

use Illuminate\Database\Seeder;

class AlgorithmSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('algorithms')->delete();
        \DB::table('algorithms')->insert(array (
            0 => 
            array (
                'id' => 1,
                'text' => 'Empty',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => 3,
                'onNegative' => 2,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => 'religion_sect',
                'conditionalOperator' => '=',
                'conditionalValue' => 'CATHOLIC',
                'delay' => 0,
                'series' => NULL,
                'created_at' => '2021-03-21 12:38:55',
                'updated_at' => '2021-04-05 14:39:51',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            1 => 
            array (
                'id' => 2,
                'text' => 'Would you like to consider other family planning methods apart from the Natural types?',
                'actionType' => 'bool',
                'positive' => 'Yes',
                'negative' => 'No',
                'onPositive' => 8,
                'onNegative' => 4,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 500,
                'series' => NULL,
                'created_at' => '2021-03-21 15:07:00',
                'updated_at' => '2021-03-22 19:33:02',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            2 => 
            array (
                'id' => 3,
                'text' => 'We noticed you\'re Catholic. Would you like to consider other family planning methods apart from the Natural types?',
                'actionType' => 'bool',
                'positive' => 'Yes',
                'negative' => 'No',
                'onPositive' => 8,
                'onNegative' => 4,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 500,
                'series' => NULL,
                'created_at' => '2021-03-21 15:09:39',
                'updated_at' => '2021-03-22 19:33:12',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            3 =>
            array (
                'id' => 4,
                'text' => 'Empty',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => 5,
                'onNegative' => 6,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => 'gender',
                'conditionalOperator' => '=',
                'conditionalValue' => 'MALE',
                'delay' => 0,
                'series' => NULL,
                'created_at' => '2021-03-21 15:22:21',
                'updated_at' => '2021-03-22 19:33:13',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y',
            ),
            4 => 
            array (
                'id' => 5,
                'text' => 'The Natural Family Planning Methods include: Withdrawal method, and Fertile Period Monitor. As a man the withdrawal method is the best contraceptive plan for you. You should withdraw your penis from your partner\'s vagina and ejaculate outside the vagina.',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => NULL,
                'onNegative' => NULL,
                'nextMove' => 7,
                'tempPlan' => 'WITHDRAWAL_METHOD',
                'conditionalFactor' => '',
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 1000,
                'series' => NULL,
                'created_at' => '2021-03-21 15:30:15',
                'updated_at' => '2021-03-22 19:33:15',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            5 => 
            array (
                'id' => 6,
                'text' => 'The Natural Family Planning Methods include: Withdrawal method, and Fertile Period Monitor. As a woman the Fertile Period Monitor is perfect for you.\\\\n We will proceed to setting up your calendar.',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => NULL,
                'onNegative' => NULL,
                'nextMove' => 7,
                'tempPlan' => 'FERTILE_PERIOD_MONITOR',
                'conditionalFactor' => '',
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 1000,
                'series' => NULL,
                'created_at' => '2021-03-21 15:31:06',
                'updated_at' => '2021-03-22 19:33:16',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            6 => 
            array (
                'id' => 7,
                'text' => 'Empty',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => 9,
                'onNegative' => 10,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => 'gender',
                'conditionalOperator' => '=',
                'conditionalValue' => 'MALE',
                'delay' => 0,
                'series' => NULL,
                'created_at' => '2021-03-21 15:39:25',
                'updated_at' => '2021-03-22 19:33:16',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            7 => 
            array (
                'id' => 8,
                'text' => 'Great, Let\'s find out what contraceptive plan is right for you.',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => NULL,
                'onNegative' => NULL,
                'nextMove' => 11,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 1000,
                'series' => NULL,
                'created_at' => '2021-03-21 15:40:47',
                'updated_at' => '2021-03-22 19:33:17',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            8 => 
            array (
                'id' => 9,
                'text' => 'All Set! The Best Contraceptive Plan for you is set. Hold on while we set up your space.',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => NULL,
                'onNegative' => NULL,
                'nextMove' => 15,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 1000,
                'series' => NULL,
                'created_at' => '2021-03-21 18:04:24',
                'updated_at' => '2021-03-22 19:33:19',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            9 => 
            array (
                'id' => 10,
                'text' => 'What\'s the average number of days that make up your menstrual cycle?',
                'actionType' => 'input',
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => NULL,
                'onNegative' => NULL,
                'nextMove' => 21,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 500,
                'series' => NULL,
                'created_at' => '2021-03-21 19:16:09',
                'updated_at' => '2021-03-22 19:33:20',
                'deleted_at' => NULL,
                'stateValue' => 'cycleLength',
                'label' => 'Cycle Length',
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            10 => 
            array (
                'id' => 11,
                'text' => 'Empty',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => 12,
                'onNegative' => 13,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => 'gender',
                'conditionalOperator' => '=',
                'conditionalValue' => 'MALE',
                'delay' => 0,
                'series' => NULL,
                'created_at' => '2021-03-22 05:08:57',
                'updated_at' => '2021-03-22 19:33:21',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            11 => 
            array (
                'id' => 12,
                'text' => 'Are you looking for a temporary solution or a permanent one?',
                'actionType' => 'bool',
                'positive' => 'Temporary',
                'negative' => 'Permanent',
                'onPositive' => 16,
                'onNegative' => 17,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 500,
                'series' => NULL,
                'created_at' => '2021-03-22 05:13:10',
                'updated_at' => '2021-03-22 19:33:22',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            12 => 
            array (
                'id' => 13,
                'text' => 'Do you have any history of yellowness of the eyes or Liver\/gall bladder problems?',
                'actionType' => 'bool',
                'positive' => 'Yes',
                'negative' => 'No',
                'onPositive' => 19,
                'onNegative' => 18,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 250,
                'series' => NULL,
                'created_at' => '2021-03-22 05:15:00',
                'updated_at' => '2021-03-22 19:33:24',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            13 => 
            array (
                'id' => 15,
                'text' => 'End',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => NULL,
                'onNegative' => NULL,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 0,
                'series' => NULL,
                'created_at' => '2021-03-22 05:20:05',
                'updated_at' => '2021-03-22 19:33:24',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            14 => 
            array (
                'id' => 16,
                'text' => 'The temporary contraceptive method for men is condoms. The pregnancy rate of condoms is 2% per year. The best contraceptive plan for you is the use of condoms.',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => NULL,
                'onNegative' => NULL,
                'nextMove' => 9,
                'tempPlan' => 'MALE_BARRIER',
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 1000,
                'series' => NULL,
                'created_at' => '2021-03-22 05:24:09',
                'updated_at' => '2021-03-22 19:33:25',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            15 => 
            array (
                'id' => 17,
                'text' => 'The permanent contraceptive method for men is a Vasectomy. Vasectomy is a surgical procedure for male sterilization or permanent birth control. The best contraceptive plan for you is to get a Vasectomy. This is a surgical procedure, therefore adequate counselling from a healthcare professional is required',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => NULL,
                'onNegative' => NULL,
                'nextMove' => 9,
                'tempPlan' => 'MALE_VASECTOMY',
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 1500,
                'series' => NULL,
                'created_at' => '2021-03-22 05:28:33',
                'updated_at' => '2021-03-22 19:33:27',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            16 => 
            array (
                'id' => 18,
                'text' => 'Are you currently taking any medications for seizures?',
                'actionType' => 'bool',
                'positive' => 'Yes',
                'negative' => 'No',
                'onPositive' => 19,
                'onNegative' => 20,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 250,
                'series' => NULL,
                'created_at' => '2021-03-22 05:35:26',
                'updated_at' => '2021-03-22 19:33:28',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            17 => 
            array (
                'id' => 19,
                'text' => 'The combined oral contraceptive pill, often referred to as the birth control pill or \"the pill\", is a type of birth control that is designed to be taken orally by women. This is the best contraceptive plan for you.',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => NULL,
                'onNegative' => NULL,
                'nextMove' => 10,
                'tempPlan' => 'COMBINED_ORAL',
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 500,
                'series' => NULL,
                'created_at' => '2021-03-22 05:38:09',
                'updated_at' => '2021-03-22 19:33:28',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            18 => 
            array (
                'id' => 20,
                'text' => 'Is there any history of breast cancer with you or in your family?',
                'actionType' => 'bool',
                'positive' => 'Yes',
                'negative' => 'No',
                'onPositive' => 19,
                'onNegative' => 23,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 250,
                'series' => NULL,
                'created_at' => '2021-03-22 05:41:17',
                'updated_at' => '2021-03-22 19:33:30',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            19 => 
            array (
                'id' => 21,
                'text' => 'How many days does each Menstrual Period last?',
                'actionType' => 'input',
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => NULL,
                'onNegative' => NULL,
                'nextMove' => 22,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 500,
                'series' => NULL,
                'created_at' => '2021-03-22 06:10:20',
                'updated_at' => '2021-03-22 19:33:31',
                'deleted_at' => NULL,
                'stateValue' => 'periodLength',
                'label' => 'Average Period Days',
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            20 => 
            array (
                'id' => 22,
                'text' => 'When did your last Menstrual Period begin?',
                'actionType' => 'date',
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => NULL,
                'onNegative' => NULL,
                'nextMove' => 9,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 500,
                'series' => NULL,
                'created_at' => '2021-03-22 06:22:50',
                'updated_at' => '2021-03-22 19:33:32',
                'deleted_at' => NULL,
                'stateValue' => 'lastPeriodAt',
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            21 => 
            array (
                'id' => 23,
                'text' => 'Empty',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => 24,
                'onNegative' => 25,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => 'pregnancy_status',
                'conditionalOperator' => '=',
                'conditionalValue' => '1',
                'delay' => 0,
                'series' => NULL,
                'created_at' => '2021-03-22 06:51:09',
                'updated_at' => '2021-03-22 19:33:32',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => 'true',
                'progestogenPossibleDir' => 'negative',
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            22 => 
            array (
                'id' => 24,
                'text' => 'Is your baby less than 6 weeks old?',
                'actionType' => 'bool',
                'positive' => 'Yes',
                'negative' => 'No',
                'onPositive' => 19,
                'onNegative' => 25,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 250,
                'series' => NULL,
                'created_at' => '2021-03-22 06:52:05',
                'updated_at' => '2021-03-22 19:33:34',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => 'true',
                'progestogenPossibleDir' => 'negative',
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            23 => 
            array (
                'id' => 25,
                'text' => 'Combined Oral Contraceptive Pills stop eggs being made, so no egg is released from the ovary. It is normally 92% effective, and side effects include: irregular menstruation and acne. Progestogen-only pills work mainly by thickening the mucus in the cervix so sperm can\'t travel through it. It is typically 92% effective, and the side effect is irregular menstruation.',
                'actionType' => NULL,
                'positive' => NULL,
                'negative' => NULL,
                'onPositive' => NULL,
                'onNegative' => NULL,
                'nextMove' => 26,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 2500,
                'series' => NULL,
                'created_at' => '2021-03-22 07:40:09',
                'updated_at' => '2021-03-22 19:33:36',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            24 => 
            array (
                'id' => 26,
                'text' => 'What type of contraception would you prefer',
                'actionType' => 'bool',
                'positive' => 'Combined Oral',
                'negative' => 'Progestogen-Only',
                'onPositive' => 27,
                'onNegative' => 10,
                'nextMove' => NULL,
                'tempPlan' => '',
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 350,
                'series' => NULL,
                'created_at' => '2021-03-22 14:48:19',
                'updated_at' => '2021-03-22 19:33:37',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => 'PROGESTOGEN_ONLY',
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            25 =>
            array (
                'id' => 27,
                'text' => 'Are you hypertensive or diabetic?',
                'actionType' => 'bool',
                'positive' => 'Yes',
                'negative' => 'No',
                'onPositive' => 19,
                'onNegative' => 28,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 250,
                'series' => NULL,
                'created_at' => '2021-03-22 15:34:29',
                'updated_at' => '2021-03-22 19:33:42',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            26 => 
            array (
                'id' => 28,
                'text' => 'Do you have migraines often?',
                'actionType' => 'bool',
                'positive' => 'Yes',
                'negative' => 'No',
                'onPositive' => 19,
                'onNegative' => 29,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 250,
                'series' => NULL,
                'created_at' => '2021-03-22 15:35:53',
                'updated_at' => '2021-03-22 19:33:41',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            27 => 
            array (
                'id' => 29,
                'text' => 'Have you ever had a stroke or heart disease?',
                'actionType' => 'bool',
                'positive' => 'Yes',
                'negative' => 'No',
                'onPositive' => 19,
                'onNegative' => 30,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 250,
                'series' => NULL,
                'created_at' => '2021-03-22 15:37:04',
                'updated_at' => '2021-03-22 19:33:40',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            28 => 
            array (
                'id' => 30,
                'text' => 'Are you taking rifampicin/rifabutin for tuberculosis?',
                'actionType' => 'bool',
                'positive' => 'Yes',
                'negative' => 'No',
                'onPositive' => 19,
                'onNegative' => 31,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 250,
                'series' => NULL,
                'created_at' => '2021-03-22 15:37:55',
                'updated_at' => '2021-03-22 19:33:40',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => NULL,
                'tempPlanDirP' => NULL,
                'active' => 'Y'
            ),
            29 => 
            array (
                'id' => 31,
                'text' => 'The best contraceptive plans for you are the Combined Hormonal Contraceptives. Would you prefer to take the pills or wear patches\/vaginal-rings. The Patches\/Vaginal-Rings are not readily available in Nigeria',
                'actionType' => 'bool',
                'positive' => 'Pills',
                'negative' => 'Patches/Vaginal-Rings',
                'onPositive' => 10,
                'onNegative' => 10,
                'nextMove' => NULL,
                'tempPlan' => NULL,
                'conditionalFactor' => NULL,
                'conditionalOperator' => NULL,
                'conditionalValue' => NULL,
                'delay' => 350,
                'series' => NULL,
                'created_at' => '2021-03-22 15:41:04',
                'updated_at' => '2021-03-22 19:33:39',
                'deleted_at' => NULL,
                'stateValue' => NULL,
                'label' => NULL,
                'progestogenPossible' => NULL,
                'progestogenPossibleDir' => NULL,
                'tempPlanDirN' => 'COMBINED_PATCHES',
                'tempPlanDirP' => 'COMBINED_ORAL',
                'active' => 'Y'
            ),
        ));
    }
}
